on:
  push:
    branches:
      - main

jobs:
  my_job:
    name: Publish blog to dev.to
    permissions:
      contents: write # this lets the bot update the post in github
    runs-on: ubuntu-latest # ubuntu costs half the price of windows

    steps:
      - uses: actions/checkout@v3 # checks out my code to the actions build
      - name: Publish articles on Dev.to
        uses: sinedied/publish-devto@v2
        with:
          devto_key: ${{ secrets.DEVTO_API_KEY }} # the secret you setup
          github_token: ${{ secrets.GITHUB_TOKEN }} # this is an inbuilt secret by github
          files: "src/**/*.md"
          branch: main
          conventional_commits: true
          dry_run: false # set this to true if you want to do a dry run
